/*
 * @name Assets
 * @description Store all asset urls in here
 * @author Riko Ophorst
 */
Game.Assets = {
	AssetList: [
		Utils.Assets.Images + 'level/sprWorld.png',
		Utils.Assets.Images + 'level/characters/sprCharacterWalk.png',
		Utils.Assets.Images + 'level/characters/sprCharacterSlam.png',
		Utils.Assets.Images + 'level/characters/sprCharacterGodSmash.png',
		Utils.Assets.Images + 'level/characters/sprCharacter180.png',
		Utils.Assets.Images + 'level/characters/sprGoblinWalk.png',
		Utils.Assets.Images + 'level/characters/sprMinerWalk.png',
		Utils.Assets.Images + 'level/characters/sprMinerMine.png',
		Utils.Assets.Images + 'level/characters/sprGoblinBossWalk.png',
		Utils.Assets.Images + 'level/sprPuff.png',
		Utils.Assets.Images + 'level/ui/sprGui.png',
		Utils.Assets.Images + 'level/ui/sprStabilityBar.png',
		Utils.Assets.Images + 'level/ui/sprCritical.png',
		Utils.Assets.Images + 'level/ui/sprGameOver.png',
		Utils.Assets.Images + 'level/characters/sprHammer.png',
		Utils.Assets.Images + 'level/bgLevel.png',
		Utils.Assets.Images + 'level/bgMountains.png',
		Utils.Assets.Images + 'level/bgTreeLine1.png',
		Utils.Assets.Images + 'level/bgTreeLine2.png',
		Utils.Assets.Images + 'level/sprGround.png',
		Utils.Assets.Images + 'level/fgClouds.png',
		Utils.Assets.Images + 'level/particles/partRock1.png',
		Utils.Assets.Images + 'level/particles/partRock2.png',
		Utils.Assets.Images + 'level/particles/partRock3.png',
		Utils.Assets.Images + 'level/particles/partRock4.png',
		Utils.Assets.Images + 'level/particles/partRock5.png',
		Utils.Assets.Images + 'level/particles/partFlash.png',
		Utils.Assets.Images + 'level/particles/partFlash.png',
		Utils.Assets.Images + 'level/sprLava1.png',
		Utils.Assets.Images + 'level/sprLava2.png',
		Utils.Assets.Images + 'level/sprLava3.png',
		Utils.Assets.Images + 'level/sprRedGlow.png',
		Utils.Assets.Images + 'level/sprFlare1.png',
		Utils.Assets.Images + 'level/sprFlare2.png',
		Utils.Assets.Images + 'level/sprFlare3.png',
		Utils.Assets.Images + 'level/sprFlare4.png',
		Utils.Assets.Images + 'level/sprFlare5.png',
		Utils.Assets.Images + 'level/sprFlare6.png',
		Utils.Assets.Images + 'level/sprFlare7.png',
		Utils.Assets.Images + 'level/sprFlare8.png',
		Utils.Assets.Images + 'level/sprFlare9.png',
		Utils.Assets.Images + 'level/sprFlare10.png',
		Utils.Assets.Images + 'level/sprFlare11.png',
		Utils.Assets.Images + 'level/characters/sprCharacter360Flame.png',
		Utils.Assets.Images + 'level/characters/sprCharacter360Teleport.png',
		Utils.Assets.Images + 'level/ui/sprLogo.png',
		Utils.Assets.Images + 'level/ui/sprLogoBackground.png',
		Utils.Assets.Images + 'level/ui/sprLogoAnd.png',
	]
};